version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: feedback-postgres
    environment:
      POSTGRES_DB: feedback_platform
      POSTGRES_USER: tech_challenge4
      POSTGRES_PASSWORD: grupo13
    ports:
      - "5434:5432"
    volumes:
      - feedback_postgres_data:/var/lib/postgresql/data

volumes:
  feedback_postgres_data:
