services:
  postgres:
    image: postgres:16
    container_name: analytics-postgres
    environment:
      POSTGRES_DB: analytics_platform
      POSTGRES_USER: tech_challenge4
      POSTGRES_PASSWORD: grupo13
    ports:
      - "5432:5432"
    volumes:
      - analytics_postgres_data:/var/lib/postgresql/data

volumes:
  analytics_postgres_data:
